// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-JBfV-ks9N7r93ptFsK4NaBPkIsVnV6o',
    appId: '1:33804315343:web:934416eda09e9b54d925ba',
    messagingSenderId: '33804315343',
    projectId: 'prueba-tcs',
    authDomain: 'prueba-tcs.firebaseapp.com',
    storageBucket: 'prueba-tcs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFJKtJ_Rq87vFk4XRoiNNpCwo-hqxXVvo',
    appId: '1:33804315343:android:fc891ea29d900149d925ba',
    messagingSenderId: '33804315343',
    projectId: 'prueba-tcs',
    storageBucket: 'prueba-tcs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVgqahXT_paDBncwZ7If2fpLLmXLvQqQ',
    appId: '1:33804315343:ios:d1220a679a9a4b89d925ba',
    messagingSenderId: '33804315343',
    projectId: 'prueba-tcs',
    storageBucket: 'prueba-tcs.firebasestorage.app',
    iosBundleId: 'com.example.pruebaTcs',
  );
}
